version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - FLASK_APP
      - FLASK_ENV
    env_file:
      - .env.example
    command: flask run --host=0.0.0.0 --port=80
    
  